<?php

class AiBridgeCombinationHandler
{
    private const FIELDS = array('attributes','reference','ean13','isbn','upc','price_impact','wholesale_price','weight_impact','minimal_quantity','available_date','default_on');
    public function normalize($value, Product $product, $languageId)
    {
        if (!is_array($value) || array_diff(array_keys($value), array('update')) || !isset($value['update']) || !is_array($value['update'])) return null;
        $result=array();$seen=array();
        foreach($value['update'] as $entry){if(!is_array($entry)||!isset($entry['id_product_attribute']))return null;$id=$this->positive($entry['id_product_attribute']);$combination=$id?new Combination($id):null;if($id===null||isset($seen[$id])||!Validate::isLoadedObject($combination)||(int)$combination->id_product!==(int)$product->id)return null;$out=array('id_product_attribute'=>$id);foreach($entry as $field=>$v){if($field==='id_product_attribute')continue;if(!in_array($field,self::FIELDS,true))return null;if($field==='attributes'){$v=$this->attributes($v,$languageId);if($v===null||$product->productAttributeExists($v,$id,Context::getContext(),false,true))return null;$out[$field]=$v;continue;}if(in_array($field,array('price_impact','wholesale_price','weight_impact'),true)){if(!is_numeric($v))return null;$out[$field]=(float)$v;continue;}if($field==='minimal_quantity'){if(is_bool($v)||!(is_int($v)||(is_string($v)&&ctype_digit($v)))||(int)$v<1)return null;$out[$field]=(int)$v;continue;}if($field==='available_date'){if($v!==''&&(!is_string($v)||!Validate::isDateFormat($v)))return null;$out[$field]=$v;continue;}if($field==='default_on'){if(!in_array($v,array(0,1,'0','1'),true))return null;$out[$field]=(int)$v;continue;}if(!is_string($v)||($field==='reference'&&Tools::strlen($v)>64)||($field==='ean13'&&!($v===''||Validate::isEan13($v)))||($field==='isbn'&&!($v===''||Validate::isIsbn($v)))||($field==='upc'&&!($v===''||Validate::isUpc($v))))return null;$out[$field]=$v;}if(count($out)===1)return null;$seen[$id]=true;$result[]=$out;}usort($result,function($a,$b){return $a['id_product_attribute']<=>$b['id_product_attribute'];});return array('update'=>$result);
    }
    public function read(Product $product,$languageId){$result=array();foreach((array)$product->getAttributeCombinations($languageId,false) as $row){$id=(int)$row['id_product_attribute'];if(!isset($result[$id]))$result[$id]=array('id_product_attribute'=>$id,'attributes'=>array(),'reference'=>(string)$row['reference'],'ean13'=>(string)$row['ean13'],'isbn'=>(string)$row['isbn'],'upc'=>(string)$row['upc'],'price_impact'=>(float)$row['price'],'wholesale_price'=>(float)$row['wholesale_price'],'weight_impact'=>(float)$row['weight'],'minimal_quantity'=>(int)$row['minimal_quantity'],'available_date'=>(string)$row['available_date'],'default_on'=>(int)!empty($row['default_on']));$result[$id]['attributes'][]=(int)$row['id_attribute'];}foreach($result as &$r){sort($r['attributes'],SORT_NUMERIC);}unset($r);ksort($result);return $result;}
    public function capture(Product $product,array $ops,$languageId){$all=$this->read($product,$languageId);$out=array();foreach($ops['update'] as $entry)$out[$entry['id_product_attribute']]=$all[$entry['id_product_attribute']];return $out;}
    public function apply(Product $product,array $ops,$languageId){foreach($ops['update'] as $entry){$c=new Combination((int)$entry['id_product_attribute']);foreach(array('reference','ean13','isbn','upc') as $f)if(isset($entry[$f]))$c->{$f}=$entry[$f];foreach(array('price_impact'=>'price','wholesale_price'=>'wholesale_price','weight_impact'=>'weight','minimal_quantity'=>'minimal_quantity','available_date'=>'available_date','default_on'=>'default_on')as$f=>$p)if(array_key_exists($f,$entry))$c->{$p}=$entry[$f];if(!$c->update())return false;if(isset($entry['attributes'])&&!$c->setAttributes($entry['attributes']))return false;if(isset($entry['default_on'])&&$entry['default_on']===1&&!$product->setDefaultAttribute($c->id))return false;}return $this->ensureDefault($product);}
    public function verify(Product $product,array $ops,$languageId){$current=$this->read($product,$languageId);$defaults=0;foreach($current as $r)$defaults+=(int)$r['default_on'];if($current&&$defaults!==1)return false;foreach($ops['update']as$entry){if(!isset($current[$entry['id_product_attribute']]))return false;foreach($entry as$f=>$v){if($f!=='id_product_attribute'&&$current[$entry['id_product_attribute']][$f]!==$v)return false;}}return true;}
    public function restore(Product $product,array $snapshot,$languageId){$ops=array('update'=>array_values($snapshot));return $this->apply($product,$ops,$languageId)&&$this->verify($product,$ops,$languageId);}
    public function buildChange(Product $product,$value,$languageId){$normalized=$this->normalize($value,$product,$languageId);$current=$this->read($product,$languageId);$changes=array();if($normalized!==null)foreach($normalized['update']as$e){$old=$current[$e['id_product_attribute']];$delta=array();foreach($e as$f=>$v)if($f!=='id_product_attribute'&&$old[$f]!==$v)$delta[$f]=array('current'=>$old[$f],'proposed'=>$v);if($delta)$changes[] = array('id_product_attribute'=>$e['id_product_attribute'],'fields'=>$delta);}return array('field'=>'combinations','current'=>$current,'proposed'=>$normalized===null?$value:$normalized,'changed'=>!empty($changes),'changes'=>$changes,'validation'=>array('ok'=>$normalized!==null,'errors'=>$normalized===null?array('Invalid combination update payload.'):array()));}
    private function attributes($v,$lang){if(!is_array($v)||!$v)return null;$map=array();foreach((array)AttributeGroup::getAttributesGroups((int)$lang)as$g)foreach((array)AttributeGroup::getAttributes((int)$lang,(int)$g['id_attribute_group'])as$a)$map[(int)$a['id_attribute']]=(int)$g['id_attribute_group'];$ids=array();$groups=array();foreach($v as$id){$id=$this->positive($id);if($id===null||!isset($map[$id])||isset($groups[$map[$id]]))return null;$ids[]=$id;$groups[$map[$id]]=1;}sort($ids,SORT_NUMERIC);return $ids;}
    private function ensureDefault(Product $p){$rows=Product::getProductAttributesIds((int)$p->id);if(!$rows)return true;$defaults=0;$default=0;foreach($rows as$row){$c=new Combination((int)$row['id_product_attribute']);if(Validate::isLoadedObject($c)&&(int)$c->default_on===1){$defaults++;$default=(int)$c->id;}}return $defaults===1?$p->setDefaultAttribute($default):$p->setDefaultAttribute((int)$rows[0]['id_product_attribute']);}
    private function positive($v){return(is_int($v)&&$v>0)?$v:((is_string($v)&&ctype_digit($v)&&(int)$v>0)?(int)$v:null);}
}
